language: node_js
node_js:
  - "8"
  - "10"
addons:
    code_climate:
        repo_token: $secret_key
env:
  matrix:
  - REACT=16.6
sudo: false

before_script:
  - npm install -g codeclimate-test-reporter

script:
  - npm run test
  
after_script:
  - COVERALLS_REPO_TOKEN=$coveralls_repo_token npm run coveralls

after_success:
  - npm run coverage
  - codeclimate-test-reporter < ./coverage/lcov.info



