export const LOGIN = "LOGIN";
export const USER_NOT_FOUND = "USER_NOT_FOUND";
export const ERROR = "ERROR";
export const LOADING = "LOADING";
export const SIGNUP = "SIGNUP";

const ENTRIES = {
    GET_DIARY_ENTRIES: "GET_DIARY_ENTRIES",
    VIEW_SINGLE_ENTRY: "VIEW_SINGLE_ENTRY",
    DELETE_SINGLE_ENTRY: "DELETE_SINGLE_ENTRY",
    MODIFY_SINGLE_ENTRY: "MODIFY_SINGLE_ENTRY",
    CREATE_DIARY_ENTRY: "CREATE_DIARY_ENTRY"

}

export default ENTRIES;